#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consideratePrompts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="condPrompts")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttable52(table52 instance);
    partial void Updatetable52(table52 instance);
    partial void Deletetable52(table52 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::consideratePrompts.Properties.Settings.Default.condPromptsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<table52> table52s
		{
			get
			{
				return this.GetTable<table52>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.table52")]
	public partial class table52 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Considerate_Prompts_Preconditions;
		
		private string _Warning_Location;
		
		private string _EmbeddedNavSat_In_Never_Received;
		
		private string _EmbeddedNavSat_In_Missing;
		
		private string _EmbeddedNavSat_In;
		
		private string _WaypntsActive_In_Never_Received;
		
		private string _WaypntsActive_In_Missing;
		
		private string _WaypntsActive_In;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnConsiderate_Prompts_PreconditionsChanging(string value);
    partial void OnConsiderate_Prompts_PreconditionsChanged();
    partial void OnWarning_LocationChanging(string value);
    partial void OnWarning_LocationChanged();
    partial void OnEmbeddedNavSat_In_Never_ReceivedChanging(string value);
    partial void OnEmbeddedNavSat_In_Never_ReceivedChanged();
    partial void OnEmbeddedNavSat_In_MissingChanging(string value);
    partial void OnEmbeddedNavSat_In_MissingChanged();
    partial void OnEmbeddedNavSat_InChanging(string value);
    partial void OnEmbeddedNavSat_InChanged();
    partial void OnWaypntsActive_In_Never_ReceivedChanging(string value);
    partial void OnWaypntsActive_In_Never_ReceivedChanged();
    partial void OnWaypntsActive_In_MissingChanging(string value);
    partial void OnWaypntsActive_In_MissingChanged();
    partial void OnWaypntsActive_InChanging(string value);
    partial void OnWaypntsActive_InChanged();
    #endregion
		
		public table52()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Considerate Prompts Preconditions]", Storage="_Considerate_Prompts_Preconditions", DbType="NVarChar(50)")]
		public string Considerate_Prompts_Preconditions
		{
			get
			{
				return this._Considerate_Prompts_Preconditions;
			}
			set
			{
				if ((this._Considerate_Prompts_Preconditions != value))
				{
					this.OnConsiderate_Prompts_PreconditionsChanging(value);
					this.SendPropertyChanging();
					this._Considerate_Prompts_Preconditions = value;
					this.SendPropertyChanged("Considerate_Prompts_Preconditions");
					this.OnConsiderate_Prompts_PreconditionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Warning Location]", Storage="_Warning_Location", DbType="NVarChar(50)")]
		public string Warning_Location
		{
			get
			{
				return this._Warning_Location;
			}
			set
			{
				if ((this._Warning_Location != value))
				{
					this.OnWarning_LocationChanging(value);
					this.SendPropertyChanging();
					this._Warning_Location = value;
					this.SendPropertyChanged("Warning_Location");
					this.OnWarning_LocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[EmbeddedNavSat In Never Received]", Storage="_EmbeddedNavSat_In_Never_Received", DbType="NVarChar(50)")]
		public string EmbeddedNavSat_In_Never_Received
		{
			get
			{
				return this._EmbeddedNavSat_In_Never_Received;
			}
			set
			{
				if ((this._EmbeddedNavSat_In_Never_Received != value))
				{
					this.OnEmbeddedNavSat_In_Never_ReceivedChanging(value);
					this.SendPropertyChanging();
					this._EmbeddedNavSat_In_Never_Received = value;
					this.SendPropertyChanged("EmbeddedNavSat_In_Never_Received");
					this.OnEmbeddedNavSat_In_Never_ReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[EmbeddedNavSat In Missing]", Storage="_EmbeddedNavSat_In_Missing", DbType="NVarChar(50)")]
		public string EmbeddedNavSat_In_Missing
		{
			get
			{
				return this._EmbeddedNavSat_In_Missing;
			}
			set
			{
				if ((this._EmbeddedNavSat_In_Missing != value))
				{
					this.OnEmbeddedNavSat_In_MissingChanging(value);
					this.SendPropertyChanging();
					this._EmbeddedNavSat_In_Missing = value;
					this.SendPropertyChanged("EmbeddedNavSat_In_Missing");
					this.OnEmbeddedNavSat_In_MissingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[EmbeddedNavSat In]", Storage="_EmbeddedNavSat_In", DbType="NVarChar(50)")]
		public string EmbeddedNavSat_In
		{
			get
			{
				return this._EmbeddedNavSat_In;
			}
			set
			{
				if ((this._EmbeddedNavSat_In != value))
				{
					this.OnEmbeddedNavSat_InChanging(value);
					this.SendPropertyChanging();
					this._EmbeddedNavSat_In = value;
					this.SendPropertyChanged("EmbeddedNavSat_In");
					this.OnEmbeddedNavSat_InChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[WaypntsActive In Never Received]", Storage="_WaypntsActive_In_Never_Received", DbType="NVarChar(50)")]
		public string WaypntsActive_In_Never_Received
		{
			get
			{
				return this._WaypntsActive_In_Never_Received;
			}
			set
			{
				if ((this._WaypntsActive_In_Never_Received != value))
				{
					this.OnWaypntsActive_In_Never_ReceivedChanging(value);
					this.SendPropertyChanging();
					this._WaypntsActive_In_Never_Received = value;
					this.SendPropertyChanged("WaypntsActive_In_Never_Received");
					this.OnWaypntsActive_In_Never_ReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[WaypntsActive In Missing]", Storage="_WaypntsActive_In_Missing", DbType="NVarChar(50)")]
		public string WaypntsActive_In_Missing
		{
			get
			{
				return this._WaypntsActive_In_Missing;
			}
			set
			{
				if ((this._WaypntsActive_In_Missing != value))
				{
					this.OnWaypntsActive_In_MissingChanging(value);
					this.SendPropertyChanging();
					this._WaypntsActive_In_Missing = value;
					this.SendPropertyChanged("WaypntsActive_In_Missing");
					this.OnWaypntsActive_In_MissingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[WaypntsActive In]", Storage="_WaypntsActive_In", DbType="NVarChar(50)")]
		public string WaypntsActive_In
		{
			get
			{
				return this._WaypntsActive_In;
			}
			set
			{
				if ((this._WaypntsActive_In != value))
				{
					this.OnWaypntsActive_InChanging(value);
					this.SendPropertyChanging();
					this._WaypntsActive_In = value;
					this.SendPropertyChanged("WaypntsActive_In");
					this.OnWaypntsActive_InChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
